### ISSUE TITLE
Doesn't show the attributes of a relationship

### ISSUE THREAD

**Issue by jonquintero** [timacdonald/json-api#12]
Hi Tim.

Do you have any idea why don't the attributes of a relationship? I'm testing two API's and both with the same result. I follow the instructions but doesn't work.
![12-4-2022 20 4 35 1](https://user-images.githubusercontent.com/11522657/163074350-a8d8e6e0-34e8-4dd6-af79-a200d86a425c.jpg)

I would appreciate any help

**Comment by jonquintero** [comment]
Sorry I saw that you are  WIP in some issues...would be great have the links in the relationships

**Comment by jonquintero** [comment]
Hi Tim, thank you for answer me.

First this is my resource 

<?php

namespace App\Http\Resources;

use App\ValueObjects\Amount;
use Illuminate\Http\Request;
use TiMacDonald\JsonApi\JsonApiResource;

class EmployeeResource extends JsonApiResource
{
    public function toAttributes(Request $request): array
    {
        return [
            'fullName' => $this->full_name,
            'email' => $this->email,
            'jobTitle' => $this->job_title,
            'payment' => [
                'type' => $this->payment_type->type(),
                'amount' => Amount::from($this->payment_type->amount())->toArray(),
            ],
        ];
    }

    public function toRelationships(Request $request): array
    {
        return [
            'department' => fn () => new DepartmentResource($this->department),
            'paychecks' => fn () => PaycheckResource::collection($this->paychecks),
        ];
    }

    public function toLinks(Request $request): array
    {
        return [
            'self' => route('employees.show', ['employee' => $this->uuid]),
        ];
    }
}

**Comment by jonquintero** [comment]
Hi Tim, thank you for answer me

This is the resources
https://github.com/jonquintero/api-test-pest/blob/8593ed077c166a671aa3aaa9d1abe7c7901dd7de/app/Http/Resources/EmployeeResource.php#L1

**Comment by jonquintero** [comment]
if you see, I'm using   'department' => fn () => new DepartmentResource($this->department), and not DepartmentResource::minimalAttributes().

Why not? Because  the behavior is so weird, only show the attributes from the first record and the others records disappear
![14-4-2022 12 4 2 1](https://user-images.githubusercontent.com/11522657/163435149-8321b685-b7a5-45e0-b9d1-6a4b189c12de.jpg)

**Comment by DiarQoroviqi** [comment]
Hi @jonquintero did you find any solution for not showing the attributes of relation, because I have the same problem, it only shows the id and the type and an empty object of meta?

**Comment by timacdonald** [comment]
Hey folks, I believe this is cause by the relationship being `null` and not a model. When your relation is `nullable`, you should follow this pattern...

```php
return [
     'user' => fn () => optional($this->user, fn ($user) => new UserResource($user)),
];
```

This is documented: https://github.com/timacdonald/json-api#resource-relationships

Note: In an upcoming verison, this will be improved so you can just return the resource and not have to juggle it being `null`.

**Comment by ArtMin96** [comment]
I have the same problem

Not working
```php
public function toRelationships(Request $request): array
 {
    return [
        'services' => fn () => optional($this->services, fn ($services) => ServicesResource::collection($services)),
    ];
}
```

Not working
```php
public function toRelationships(Request $request): array
 {
    return [
        'services' => fn () => ServicesResource::collection($services),
    ];
}
```

Not working
```php
public $relationships = [
    'services' => ServicesResource::class,
];
```

Result
![image](https://github.com/timacdonald/json-api/assets/29732308/06d3badb-3fa4-4848-ab63-b359a37bf188)
