### ISSUE TITLE
Package requires Laravel framework instead of Illuminate packages

### ISSUE THREAD

**Issue by DannyvdSluijs** [timacdonald/json-api#13]
As highlighted in composer.json https://github.com/timacdonald/json-api/blob/c3f89eef3e6c3e6b4f46321211543acc99f5134f/composer.json#L20 this package requires laravel/framework.

Trying to use this package in a Luman application is resulting in Illuminate packages being removed and laravel/framework being installed as its replacement causing some application issues.

I think it would be relatively easy to replace the dependencies for the sub packages of Laravel framework. Before creating such an PR I wanted to check if  you would be accepting pull requests for this?

**Comment by timacdonald** [comment]
I should be able to do this for sure. Will look at that shortly.

**Comment by DannyvdSluijs** [comment]
I took the time to at least make the code changes that I think should be required in order to support Lumen. Changes still need to be tested.
