### ISSUE TITLE
Top level Meta for Collection

### ISSUE THREAD

**Issue by snellingio** [timacdonald/json-api#16]
Even though this is specifically in the To Do section, I'm making an issue for it to bump the urgency of it as I need it to pass back some additional data.

I am imagining an API that looks something like this:
`Resource::collection($data)->withMeta($meta)`

Again, if @timacdonald has a specific implementation in mind, let me know. If it sounds good in theory, I can try to take a stab at it.

**Comment by timacdonald** [comment]
Hey, just a heads up I'll be merging support for this shortly!

**Comment by timacdonald** [comment]
This is the exact API that will land in v1. Docs are being written at the moment. Thanks Sam.

**Comment by lloricode** [comment]
hi @timacdonald is this possible today? can not see on docs, thank you

**Comment by lloricode** [comment]
currently this way works
```php
        return ItemResource::collection(
            // ...
        )
            ->additional([ // << -----
                'meta' => [
                    'test_key' => 'test_value',
                ],
            ]);
```

```json
 "meta": {
        // ...
        "test_key": "test_value"
    },
```
