### ISSUE TITLE
Class "TiMacDonald\JsonApi\JsonApiResource" not found

### ISSUE THREAD

**Issue by CNSam** [timacdonald/json-api#19]
Hi there,

So i've picked up this package this morning and installed into my project, made the necessary change to my resource file and im simply getting the error:
```Class "TiMacDonald\JsonApi\JsonApiResource" not found```

This is my resource file
```
<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use TiMacDonald\JsonApi\JsonApiResource;

class PostResource extends JsonApiResource
{ 
...
```

Am I missing something here? I can see the files in the vendor folder etc but just doesn't work. I've tried composer dump-autoload and that hasn't resolved anything either.

Regards

**Comment by brunoalfred** [comment]
It seems to work just fine, would you provide more information to reproduce the issues...

**Comment by timacdonald** [comment]
Gonna close this unless we can get a reproduction repo.
