### ISSUE TITLE
To Many relationship wrong wrapped?

### ISSUE THREAD

**Issue by bolivir** [timacdonald/json-api#21]
Hi, 

Im using a relationship that is an collection. If i look into the response relationship attributes i get 
`"relationships": { "order_lines": [ { "data": { "id": "12", "type": "orderLines", "meta": [] }, "meta": [], "links": [] } ] `

When looking into the json spec it should be like 

`"comments": {
        "data": [
          { "type": "comments", "id": "5" },
          { "type": "comments", "id": "12" }
        ]
      }`

Why is it wrapping it with an array instead of wrapping the data with the array? Am i missing something or doing it wrong? Or just a bug

**Comment by bolivir** [comment]
Anyone?

**Comment by timacdonald** [comment]
Hey! you are correct.

This has been addressed in the current main branch (untagged). Will likely be tagged when I tag a v1 - hopefully soon).

**Comment by bolivir** [comment]
Thanks for the response! Will take a look and if that works i will use the untagged version untill its tagged. Already took a shot myself and got it "quick" fixed.

Thanks

**Comment by glennjacobs** [comment]
@timacdonald any idea of when v1 might be tagged?

**Comment by timacdonald** [comment]
it's 99.999999999999999% ready. just need a couple more free mornings to hack on it.

**Comment by glennjacobs** [comment]
That's pretty close! Awesome, look forward to it.

**Comment by timacdonald** [comment]
Gonna close this as it’ll be fixed in v1.
