### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by Matpewka** [timacdonald/json-api#28]
current version cannot be installed on laravel 10
![image](https://user-images.githubusercontent.com/2772816/223430749-d4aab8e5-3c43-4927-9ae4-1de3a878192f.png)
Is it planing for support?

**Comment by timacdonald** [comment]
Laravel 10 support in the v1 beta ([v1.0.0-beta.4](https://github.com/timacdonald/json-api/releases/tag/v1.0.0-beta.4)`

I recommend upgrading to it. Check out the upgrade guide.

**Comment by rmwilliams1s** [comment]
Hello, I'd like to ask a follow-up to this issue. Our production project is using this package, and we're trying to upgrade to Laravel 10 and thus also need to upgrade this package to version v1.0.0-beta.6. We're hesitant to add a beta version to our project; we would like to keep using stable versions where possible. Is there an estimate when the next stable version will be released?
