### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by muath-ye** [timacdonald/json-api#29]
![image](https://user-images.githubusercontent.com/34031333/224482524-6f1033f0-954e-4809-bbdc-2138f2ddf058.png)

**Comment by J5Dev** [comment]
yup, also just discovered the same issue... package looks awesome, just need to be able to install it.

Any chance of a version bum please @timacdonald :)

**Comment by timacdonald** [comment]
https://github.com/timacdonald/json-api/issues/28
