### ISSUE TITLE
Type is plural

### ISSUE THREAD

**Issue by rabol** [timacdonald/json-api#39]
in the respons the type is plural. Can I change that as it's not technical correct

if the return is a User, the type should ber 'user'

**Comment by timacdonald** [comment]
Hey!

`type` is conventionally a plural in the docs, but they do say they are agnostic about it.

See how to customise the type in the docs: https://github.com/timacdonald/json-api#customising-the-resource-type


```php
use TiMacDonald\JsonApi\JsonApiResource;
use Illuminate\Http\Request;

class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
        JsonApiResource::resolveTypeUsing(function (mixed $resource, Request $request): string {
            // your custom resolution logic...
        });
    }
}
```
