### ISSUE TITLE
Question about the type of the id member of resource objects according to JSON:API specifications

### ISSUE THREAD

**Issue by agnonym** [timacdonald/json-api#67]
Hello,
First of all, thank you for this fantastic package!

I have a question regarding resource identification. The JSON:API specifications state that "The values of the id, type, and lid members MUST be strings" for resource objects.

Have you considered adding support for using Hashids (which we already use in a project with your package, along with an overlay package currently in development: https://github.com/Codivores/Laravel-Modular-API) or any other mechanism to obfuscate/encode the actual id value?

Thanks again

**Comment by timacdonald** [comment]
Hi, @agnonym, that isn't really a concern of this package directly.

You can control this yourself. If you use these types of IDs on your models primary key, it will just work. If you want to change it for all models, you may use...

```php
// file: app/Providers/AppServiceProvider.php
public function boot()
{
    JsonResource::resolveIdUsing(fn ($model) => $model->my_custom_id);
 
    // ...
}
```

If you would like to only change specific resources to use your new ID you may do the following...

```php
<?php

class UserResource extends JsonResource
{
    public function toId($request)
    {
        return $this->my_custom_id;
    }
}
```

Hope that helps!

**Comment by agnonym** [comment]
Hi @timacdonald, and thank you for taking the time to respond.

That's indeed what we are doing by encoding integer IDs using a Hashids package (https://github.com/vinkla/hashids).

It’s just that, regarding the JSON:API specification which requires strings, I always feel a bit hesitant to simply cast an integer to a string 😁

Thanks again for your response and for this package!

**Comment by timacdonald** [comment]
No worries!
