### ISSUE TITLE
Laravel 9 Support Release

### ISSUE THREAD

**Issue by stephenjude** [timacdonald/json-api#9]
@timacdonald I did like you to know that I have tested the Laravel 9 support PR and all tests are passing. 

<img width="569" alt="Screenshot 2022-02-23 at 2 22 09 PM" src="https://user-images.githubusercontent.com/31182887/155327673-f8c4fc71-0549-4f7b-a831-00ba162a5b2d.png">

When are we expecting a release tag?

**Comment by timacdonald** [comment]
My bad! I had it in main but never tagged a release. Just tagged a release that supports Laravel 9.0: https://github.com/timacdonald/json-api/releases/tag/v0.2.1
